import { User, Chat, Call, Message } from '../types';

const now = new Date();

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'John Doe',
    phone: '+1 234 567 8901',
    avatar: '👨‍💼',
    bio: 'Software Developer | Coffee Lover ☕',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: '2',
    name: 'Jane Smith',
    phone: '+1 234 567 8902',
    avatar: '👩‍💻',
    bio: 'Designer | Creative Thinker 🎨',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: '3',
    name: 'Mike Johnson',
    phone: '+1 234 567 8903',
    avatar: '👨‍🎨',
    bio: 'Product Manager',
    status: 'away',
    lastSeen: new Date(now.getTime() - 3600000),
  },
  {
    id: '4',
    name: 'Sarah Williams',
    phone: '+1 234 567 8904',
    avatar: '👩‍🏫',
    bio: 'Teacher | Educator',
    status: 'offline',
    lastSeen: new Date(now.getTime() - 7200000),
  },
  {
    id: '5',
    name: 'Alex Brown',
    phone: '+1 234 567 8905',
    avatar: '👨‍🚀',
    bio: 'Developer | Tech Enthusiast',
    status: 'online',
    lastSeen: new Date(),
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: '1',
    senderId: '1',
    senderName: 'John Doe',
    content: 'Hey! How are you?',
    type: 'text',
    timestamp: new Date(now.getTime() - 300000),
    read: true,
  },
  {
    id: '2',
    senderId: '5',
    senderName: 'Alex Brown',
    content: "I'm doing great! How about you?",
    type: 'text',
    timestamp: new Date(now.getTime() - 240000),
    read: true,
  },
  {
    id: '3',
    senderId: '1',
    senderName: 'John Doe',
    content: 'Pretty good! Want to grab coffee?',
    type: 'text',
    timestamp: new Date(now.getTime() - 180000),
    read: true,
  },
  {
    id: '4',
    senderId: '2',
    senderName: 'Jane Smith',
    content: 'Sure! Tomorrow at 3pm?',
    type: 'text',
    timestamp: new Date(now.getTime() - 120000),
    read: true,
  },
];

export const DEV_TEAM_MESSAGES: Message[] = [
  {
    id: 'dev-1',
    senderId: '1',
    senderName: 'John Doe',
    senderAvatar: 'J',
    content: 'Can someone review the forward flow today?',
    type: 'text',
    timestamp: new Date(now.getTime() - 4200000),
    read: true,
  },
  {
    id: 'dev-2',
    senderId: '5',
    senderName: 'Alex Brown',
    content: 'Yes, I am checking the group chat UI first.',
    type: 'text',
    timestamp: new Date(now.getTime() - 3900000),
    read: true,
  },
  {
    id: 'dev-3',
    senderId: '2',
    senderName: 'Jane Smith',
    senderAvatar: 'J',
    content: 'Please keep the sender name visible above every incoming group message.',
    type: 'text',
    timestamp: new Date(now.getTime() - 3600000),
    read: true,
  },
  {
    id: 'dev-4',
    senderId: '3',
    senderName: 'Mike Johnson',
    senderAvatar: 'M',
    content: 'Also add the profile picture on the left side. It looks different from individual chat.',
    type: 'text',
    timestamp: new Date(now.getTime() - 3300000),
    read: true,
    replyToId: 'dev-2',
  },
  {
    id: 'dev-5',
    senderId: '5',
    senderName: 'Alex Brown',
    senderAvatar: 'A',
    content: 'Dummy data is enough for now, backend can connect later.',
    type: 'text',
    timestamp: new Date(now.getTime() - 3000000),
    read: true,
  },
];

export const MOCK_CHATS: Chat[] = [
  {
    id: '1',
    userId: '1',
    title: 'John Doe',
    avatar: '👨‍💼',
    lastMessage: 'Sure! Tomorrow at 3pm?',
    lastMessageTime: new Date(now.getTime() - 120000),
    unreadCount: 0,
    isGroup: false,
    messages: MOCK_MESSAGES,
  },
  {
    id: '2',
    userId: '2',
    title: 'Jane Smith',
    avatar: '👩‍💻',
    lastMessage: 'The design looks amazing! 🎨',
    lastMessageTime: new Date(now.getTime() - 600000),
    unreadCount: 2,
    isGroup: false,
    messages: [],
  },
  {
    id: '3',
    groupId: 'g1',
    title: 'Dev Team',
    avatar: '👥',
    lastMessage: 'Alex: Dummy data is enough for now, backend can connect later.',
    lastMessageTime: new Date(now.getTime() - 3000000),
    unreadCount: 0,
    isGroup: true,
    participants: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2], MOCK_USERS[4]],
    messages: DEV_TEAM_MESSAGES,
  },
  {
    id: '4',
    userId: '3',
    title: 'Mike Johnson',
    avatar: '👨‍🎨',
    lastMessage: 'Thanks for the update!',
    lastMessageTime: new Date(now.getTime() - 1800000),
    unreadCount: 0,
    isGroup: false,
    messages: [],
  },
  {
    id: '5',
    userId: '4',
    title: 'Sarah Williams',
    avatar: '👩‍🏫',
    lastMessage: 'See you next week!',
    lastMessageTime: new Date(now.getTime() - 2700000),
    unreadCount: 1,
    isGroup: false,
    messages: [],
  },
];

export const MOCK_CALLS: Call[] = [
  {
    id: '1',
    userId: '1',
    userName: 'John Doe',
    userAvatar: '👨‍💼',
    type: 'video',
    direction: 'incoming',
    duration: 1200,
    timestamp: new Date(now.getTime() - 3600000),
    status: 'completed',
  },
  {
    id: '2',
    userId: '2',
    userName: 'Jane Smith',
    userAvatar: '👩‍💻',
    type: 'audio',
    direction: 'outgoing',
    duration: 300,
    timestamp: new Date(now.getTime() - 7200000),
    status: 'completed',
  },
  {
    id: '3',
    userId: '3',
    userName: 'Mike Johnson',
    userAvatar: '👨‍🎨',
    type: 'video',
    direction: 'incoming',
    duration: 0,
    timestamp: new Date(now.getTime() - 10800000),
    status: 'missed',
  },
  {
    id: '4',
    userId: '4',
    userName: 'Sarah Williams',
    userAvatar: '👩‍🏫',
    type: 'audio',
    direction: 'incoming',
    duration: 600,
    timestamp: new Date(now.getTime() - 14400000),
    status: 'completed',
  },
];

export const COUNTRY_CODES = [
  { code: '+1', country: 'United States' },
  { code: '+44', country: 'United Kingdom' },
  { code: '+91', country: 'India' },
  { code: '+86', country: 'China' },
  { code: '+81', country: 'Japan' },
  { code: '+33', country: 'France' },
  { code: '+49', country: 'Germany' },
  { code: '+39', country: 'Italy' },
  { code: '+34', country: 'Spain' },
  { code: '+61', country: 'Australia' },
];
